Revert "[IT-592] add validation of OwnerEmail to stack linter (#37)"
This reverts commit 6f6ed7832c67fc5cb857841d1aff4877245415a6.

sandbox-provisioner failed with following message:
$ ./lint_stack.sh -r || travis_terminate 1
./lint_stack.sh: line 100: /usr/local/bin/aws: No such file or directory
./lint_stack.sh: line 104: /usr/bin/jq: No such file or directory
ERROR: "brian.white@sagebase.org" is an invalid OwnerEmail.  The owner email must match an existing email in jumpcloud